"""remove documents category

Revision ID: c4960317175d
Revises: da0f5731a9b0
Create Date: 2026-07-16 16:21:18.859680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4960317175d'
down_revision: Union[str, Sequence[str], None] = 'da0f5731a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('cateory')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cateory', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
