"""add document category

Revision ID: da0f5731a9b0
Revises: f596056efe74
Create Date: 2026-07-16 16:16:37.599219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0f5731a9b0'
down_revision: Union[str, Sequence[str], None] = 'f596056efe74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cateory', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('cateory')

    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sentence', sa.VARCHAR(), nullable=True),
    sa.Column('answer', sa.VARCHAR(), nullable=True),
    sa.Column('corrected_sentence', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_id'), ['id'], unique=False)

    # ### end Alembic commands ###
